# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondW.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OtherWindow(object):
    def setupUi(self, OtherWindow):
        OtherWindow.setObjectName("OtherWindow")
        OtherWindow.resize(400, 300)
        OtherWindow.setMinimumSize(QtCore.QSize(400, 300))
        OtherWindow.setMaximumSize(QtCore.QSize(418, 300))
        OtherWindow.setWindowIcon(QtGui.QIcon("icons8-cloud-64.png"))

        self.centralwidget = QtWidgets.QWidget(OtherWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(400, 300))
        self.frame.setMaximumSize(QtCore.QSize(418, 300))
        self.frame.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.cidade_entry = QtWidgets.QLineEdit(self.frame)
        self.cidade_entry.setGeometry(QtCore.QRect(20, 50, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cidade_entry.setFont(font)
        self.cidade_entry.setAutoFillBackground(False)
        self.cidade_entry.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(188, 188, 188);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}")
        self.cidade_entry.setMaxLength(32)
        self.cidade_entry.setObjectName("cidade_entry")
        self.estado_entry = QtWidgets.QLineEdit(self.frame)
        self.estado_entry.setGeometry(QtCore.QRect(20, 100, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.estado_entry.setFont(font)
        self.estado_entry.setAutoFillBackground(False)
        self.estado_entry.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"\n"
"    color: rgb(188, 188, 188);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}")
        self.estado_entry.setMaxLength(32)
        self.estado_entry.setObjectName("estado_entry")
        self.botao_copiar = QtWidgets.QPushButton(self.frame)
        self.botao_copiar.setGeometry(QtCore.QRect(220, 250, 171, 41))
        self.botao_copiar.setMinimumSize(QtCore.QSize(10, 0))
        self.botao_copiar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"\n"
"    color: rgb(188, 188, 188);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(77, 77, 77);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(117, 117, 117);\n"
"}\n"
"")
        self.botao_copiar.setObjectName("botao_copiar")

        self.lat_label = QtWidgets.QLabel(self.frame)
        self.lat_label.setGeometry(QtCore.QRect(230, 180, 131, 31))
        self.lat_label.setStyleSheet("")
        self.lat_label.setScaledContents(False)
        self.lat_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lat_label.setWordWrap(False)
        self.lat_label.setObjectName("lat_label")

        self.long_label = QtWidgets.QLabel(self.frame)
        self.long_label.setGeometry(QtCore.QRect(230, 210, 131, 31))
        self.long_label.setStyleSheet("")
        self.long_label.setScaledContents(False)
        self.long_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.long_label.setWordWrap(False)
        self.long_label.setObjectName("long_label")

        self.buscar_button = QtWidgets.QPushButton(self.frame)
        self.buscar_button.setGeometry(QtCore.QRect(260, 80, 111, 41))
        self.buscar_button.setMinimumSize(QtCore.QSize(10, 0))
        self.buscar_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"\n"
"    color: rgb(188, 188, 188);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(77, 77, 77);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(117, 117, 117);\n"
"}\n"
"")
        self.buscar_button.setObjectName("buscar_button")
        self.verticalLayout.addWidget(self.frame)
        OtherWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OtherWindow)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow)

    def retranslateUi(self, OtherWindow):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow.setWindowTitle(_translate("OtherWindow", "MainWindow"))
        self.cidade_entry.setPlaceholderText(_translate("OtherWindow", "Cidade"))
        self.estado_entry.setPlaceholderText(_translate("OtherWindow", "Estado"))
        self.botao_copiar.setText(_translate("OtherWindow", "Enviar para Área de Previsão"))
        self.lat_label.setText(_translate("OtherWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; color:#797979;\">Lat:</span></p></body></html>"))
        self.long_label.setText(_translate("OtherWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; color:#797979;\">Lon: </span></p></body></html>"))
        self.buscar_button.setText(_translate("OtherWindow", "Buscar"))
import img


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OtherWindow = QtWidgets.QMainWindow()
    ui = Ui_OtherWindow()
    ui.setupUi(OtherWindow)
    OtherWindow.show()
    sys.exit(app.exec_())
